### PR TITLE
(fix) memory issue on mac os

### PR DESCRIPTION
**Pull request by mark-antony1**
@nasaWelder

### CODE REVIEW

**Review by nasaWelder — COMMENTED** [review]
Its going to make the GUI too slow, I think.

Can you update TCL 
 The memory leak is easy to see if you use the badly out-of-date and seriously flawed system Tcl/Tk 8.5.x supplied by Apple in OS X releases since 10.6. If tkinter is linked with an up-to-date Tcl/Tk, the leak should go away. At least that's the case when using python3.5 from python.org 10.6+ installers and with ActiveTcl 8.5.18 installed. See https://www.python.org/download/mac/tcltk/ for more info.

**Comment by mark-antony1** [comment]
I updated to tcl 8.6, but I am getting the same error.

**Comment by nasaWelder** [comment]
does time.sleep(.3) work?

**Comment by needmoney90** [comment]
Merge or close?

**Comment by mark-antony1** [comment]
its better. It still looks like it will grow unboundedly, but might take a day to get to that point.

**Comment by nasaWelder** [comment]
I'd like to make this temporary fix Mac specific, since it degrades UX.

**Comment by nasaWelder** [comment]
@15chrjef  what's the result of this for a mac?

>>> import platform
>>> platform.system()
'Linux'

**Comment by mark-antony1** [comment]
in which line and which file @nasaWelder ?

**Comment by nasaWelder** [comment]
Run that code, at console. Does it return "Darwin"?

**Comment by mark-antony1** [comment]
yes

**Comment by nasaWelder** [comment]
don't merge, I made this fix+ with my PR

**Pull request closed without merging**
